# Generated by Django 5.0.2 on 2024-11-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('tel', models.DecimalField(decimal_places=0, max_digits=10)),
                ('paymentdone', models.BooleanField(default=False)),
                ('paymenttype', models.CharField(choices=[('cod', 'Cash On Delivery'), ('paypal', 'PayPal'), ('stripe', 'stripe')], max_length=20)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=20)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist')),
            ],
        ),
    ]
