# Generated by Django 5.0.2 on 2024-11-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_placedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='city',
            field=models.CharField(default='cs', max_length=15),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='state',
            field=models.CharField(default='sa', max_length=15),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
