# Generated by Django 5.0.2 on 2024-11-23 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_checkoutdetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist'),
        ),
    ]
